---
#
# ------ Environment-specific Variables ------
# You will most likely want to change the values below.

s_base_use_proxy: false
s_base_proxy_env:
  http_proxy: ""
  https_proxy: ""
# s_base_proxy_host: xx.xx.xx.xx
# s_base_proxy_port: 3128
# s_base_proxy_env:
#   http_proxy: "{{ s_base_proxy_host }}:{{ s_base_proxy_port }}"
#   https_proxy: "{{ s_base_proxy_host }}:{{ s_base_proxy_port }}"
#   PATH: /usr/local/git/bin:{{ ansible_env.PATH }}
#   # will need to change this into a variable

s_base_devops_users: true

s_base_devops_groupname: sudo

s_base_additional_packages:
  - vim
  - tree
  - tmux
  # - cronie

s_base_users:
  roozbeh:
    fullname: Roozbeh Farahbod
    git_email: research@roozbeh.ca
    git_user: roozbehf

# put hosts there which should be added to etc hosts in case no DNS is available
s_base_etc_hosts: []
#s_base_etc_hosts: [ {ip: '139.168.56.1', name: 'test1'}, {ip: '139.168.56.2', name: 'test2'}]

nginx_extra_http_options: |
  proxy_buffering    off;
  proxy_set_header   X-Real-IP $remote_addr;
  proxy_set_header   X-Scheme $scheme;
  proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header   Host $http_host;

nginx_default_release: ""

# whether to install latest nodejs ('true') or the default yum package
nodejs_latest: true
