#!/usr/bin/env bash

port=2222
ansible_inv_file=".vagrant/provisioners/ansible/inventory/vagrant_ansible_inventory"

if [ -e ${ansible_inv_file} ]
then
  port=$(cat .vagrant/provisioners/ansible/inventory/vagrant_ansible_inventory | grep 127.0.0.1 | sed 's/^.*ansible_ssh_port=\(....\)\ .*/\1/g')
fi

ssh -p $port roozbeh@127.0.0.1
