---
- hosts: all
  roles:
    - {role: base, tags: base}
    - {role: git, tags: ["base", "git"]}
    - {role: git.workspace, tags: ["base", "git"]}
    - {role: java, tags: ["base", "java"]}
    - {role: nodejs, tags: ['web_server', 'nodejs']}
    - {role: docker, tags: ['docker']}
