---
- hosts: all
  roles:
    - {role: base, tags: base}
    - {role: git, tags: ["base", "git"]}
    - {role: docker, tags: ['docker']}

    # -- you can enable the following roles
    # - {role: java, tags: ["base", "java"]}
    # - {role: gobuild, tags: ['go']}
    # - {role: ansible, tags: ['ansible']}
    # - {role: nodejs, tags: ['web_server', 'nodejs']}
