---
- include: latest_install.yml
  when: nodejs_latest

- include: package_install.yml

- name: install global packages
  npm: name={{ item }} state=present global=yes
  with_items:
    - pm2
    - bower
    - gulp-cli

- name: fix npm permissions
  file:
    path="/usr/lib/node_modules"
    group="{{ s_base_devops_groupname }}"
    mode=775
    recurse=yes
