---
- name: create folders
  file: >
    path="{{ git_workspace_dir }}/{{ item }}"
    state=directory
  with_items:
    - gitlab
    - roozbehf

- name: ensure .ssh folder exists
  file: >
    path="/root/.ssh"
    owner="root"
    mode=700
    state=directory

- name: add gitlab repo hostkey
  known_hosts: >
    name="gitlab.com"
    key="{{ lookup('file', 'gitlab.key') }}"

# - name: create repos
#   git: >
#     dest="{{ git_workspace_dir }}/{{ item.value.src }}/{{ item.key }}"
#     repo="{{ item.value.url }}"
#     update=yes
#     force=yes
#   with_dict: repos

- name: set permissions on git workspace directories
  file: >
    path="{{ git_workspace_dir }}"
    owner="{{ git_user }}"
    group="{{ git_group }}"
    recurse=yes
