---
- name: add git package
  yum: name=git state=present

- name: global git config file
  template:
    src: gitconfig.j2
    dest: /home/{{ item.key }}/.gitconfig
  with_dict: "{{ s_base_users }}"

# - name: config git post
#   shell: git config --global http.postBuffer 524288000
#   environment:
#     PATH: "/usr/local/git/bin:{{ ansible_env.PATH }}"
