---
- name: add git package
  yum: name=git state=present

- name: global git config file
  template:
    src: gitconfig.j2
    dest: /home/{{ item.key }}/.gitconfig
  with_dict: "{{ s_base_users }}"

- name: add gitlab repo hostkey
  known_hosts: >
    name="gitlab.com"
    key="{{ lookup('file', 'gitlab.key') }}"

- name: add github repo hostkey
  known_hosts: >
    name="github.com"
    key="{{ lookup('file', 'github.key') }}"
