---
- name: install Java 8
  yum: pkg=java-1.8.0-openjdk state=installed

- name: display alternatives java
  shell: "java -version 2>&1 | grep -q 1.8.0"
  register: display_alternatives_java
  changed_when: False
  failed_when: false
  ignore_errors: yes

- name: set Java version
  command: 'alternatives --install "/usr/bin/java" "java" "/usr/lib/jvm/jre-1.8.0-openjdk.x86_64/bin/java" 900000'
  when: display_alternatives_java.rc != 0

- name: set Java alternative to auto
  command: 'alternatives --auto java'
  when: display_alternatives_java.rc != 0
