---
- name: create devops group
  group: name={{ s_base_devops_groupname }}

- include: create_users.yml

- include: epel.yml
  when: (ansible_os_family == "RedHat")

- include: hosts.yml
  when: s_base_hosts

- name: disable iptables
  service: name=iptables state=stopped enabled=no
  when: s_base_disable_iptables

- include: tools.yml
